# Generated by Django 5.2.4 on 2025-07-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
