# Generated by Django 5.2.4 on 2025-07-18 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_username_user_name_delete_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="portfolio_path",
        ),
        migrations.RemoveField(
            model_name="user",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updated_at",
        ),
    ]
