# Generated by Django 5.2.4 on 2025-07-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_portfolio_path_remove_user_rating_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="tags",
            field=models.ManyToManyField(blank=True, to="users.usertag"),
        ),
    ]
