# Generated by Django 5.2.4 on 2025-07-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_usertag_user_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tags",
            field=models.ManyToManyField(to="users.usertag"),
        ),
    ]
