# Generated by Django 5.2.4 on 2025-07-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diet",
            old_name="image_path",
            new_name="image",
        ),
    ]
