# Generated by Django 5.2.4 on 2025-07-18 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0005_diet_calcium_diet_carbohydrate_diet_dietary_fiber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daydiet",
            name="day",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="daydiet",
            name="diet_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "breakfast"),
                    ("lunch", "lunch"),
                    ("dinner", "dinner"),
                    ("desert", "desert"),
                ],
                max_length=100,
            ),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
